"""changed account

Revision ID: ed9155c2e7b8
Revises: 2e4aa1dc33e8
Create Date: 2026-04-20 13:12:26.546145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9155c2e7b8'
down_revision: Union[str, Sequence[str], None] = '2e4aa1dc33e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('interest_rate', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('can_withdraw', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('deposit_end_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('cards_user_id_fkey'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cards_user_id_fkey'), 'cards', 'users', ['user_id'], ['id'])
    op.drop_column('accounts', 'deposit_end_date')
    op.drop_column('accounts', 'can_withdraw')
    op.drop_column('accounts', 'interest_rate')
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
